package io.minstyle.msgenerator.repository;

import org.springframework.data.mongodb.repository.MongoRepository;

import io.minstyle.msgenerator.model.CustomCSSModel;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Class allowing access to the DAO generated by Spring DATA.
 *
 * @author Rémi Marion
 * @version 0.0.1
 */
public interface CustomCSSRepository extends MongoRepository<CustomCSSModel, String>{

    List<CustomCSSModel> findByCreated(LocalDateTime localDateTime);
}
