package io.minstyle.msgenerator.repository;

import io.minstyle.msgenerator.model.CustomCSSModel;
import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.data.mongodb.repository.Query;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Class allowing access to the DAO generated by Spring DATA.
 *
 * @author Rémi Marion
 */
public interface CustomCSSRepository extends MongoRepository<CustomCSSModel, String> {

    List<CustomCSSModel> findByCreated(LocalDateTime localDateTime);

    @Query("{created: { $gt: ?0 }}")
    List<CustomCSSModel> getDateGreaterThan(LocalDateTime localDateTime);
}
